name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        with:
          output_dir: ./profile-3d-contrib
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./profile-3d-contrib
          git commit -m "Generate 3D profile contribution graph" || echo "No changes to commit"
          git push
